# Deploy infrastructure changes for dbowland.com
name: Update dbowland.com infrastructure

on:
  push:
    branches:
      - master

jobs:
  preview:
    name: Update infrastructure
    runs-on: ubuntu-latest
    steps:
      # Checkout latest code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install Node 16
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # Set up git commit author
      - name: Set git name and email
        run: |
          git config --local user.email "dbowland1+bot@gmail.com"
          git config --local user.name "github-actions[bot]"
      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Install Pulumi CLI
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1
      # Install dependencies
      - run: npm ci
        env:
          NODE_ENV: production
      # Execute Pulumi push
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: ./src/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      # Bump minor version
      - run: npm version minor
      # Push tag created by version bump
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
